CREATE DATABASE todo;

CREATE TABLE IF NOT EXISTS task (
  taskID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  content VARCHAR(255) NOT NULL,
  is_complete BOOL DEFAULT FALSE,
  point_value INT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS reward (
  rewardID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  total_points INT NOT NULL,
  item VARCHAR(255) NOT NULL
);

